# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0002_auto_20151220_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
