# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0004_auto_20151220_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 20, 6, 18, 34, 359627)),
        ),
    ]
