# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0006_auto_20151220_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 20, 3, 53, 49, 487485)),
        ),
    ]
