# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0006_auto_20151221_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamdb',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 22, 20, 7, 30, 465041)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2015, 12, 22)),
        ),
    ]
