# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 04:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'nineku', '0001_initial'), (b'nineku', '0002_auto_20151216_1431'), (b'nineku', '0003_auto_20151218_0435'), (b'nineku', '0004_auto_20151220_0342'), (b'nineku', '0005_auto_20151220_0346'), (b'nineku', '0006_auto_20151220_0348'), (b'nineku', '0007_auto_20151220_0353'), (b'nineku', '0008_auto_20151220_0358'), (b'nineku', '0009_auto_20151220_0401'), (b'nineku', '0010_auto_20151220_0409'), (b'nineku', '0011_auto_20151220_0409'), (b'nineku', '0012_auto_20151220_0410'), (b'nineku', '0013_auto_20151220_0411'), (b'nineku', '0014_auto_20151220_0412'), (b'nineku', '0015_auto_20151220_0412'), (b'nineku', '0016_auto_20151220_0413'), (b'nineku', '0017_auto_20151220_0414'), (b'nineku', '0018_auto_20151220_0415'), (b'nineku', '0019_auto_20151220_0417')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dreamDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('user', models.CharField(default=b'unknown user', max_length=100)),
                ('datetime', models.DateTimeField(default=datetime.date(2015, 12, 20), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.date(2015, 12, 20))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
