# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haikudb',
            name='user',
            field=models.CharField(default=b'unknown user', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2015, 12, 16)),
        ),
    ]
