# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0002_auto_20151216_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='haikuDB',
            new_name='dreamDB',
        ),
        migrations.RenameField(
            model_name='dreamdb',
            old_name='first_verse',
            new_name='dream',
        ),
        migrations.RenameField(
            model_name='dreamdb',
            old_name='second_verse',
            new_name='mood',
        ),
        migrations.RenameField(
            model_name='dreamdb',
            old_name='third_verse',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2015, 12, 18)),
        ),
    ]
