# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 03:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0003_auto_20151218_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=datetime.date(2015, 12, 20)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2015, 12, 20)),
        ),
    ]
