# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0003_auto_20151220_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
