# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0005_auto_20151220_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 19, 16, 27, 973567)),
        ),
        migrations.AlterField(
            model_name='dreamdb',
            name='dream',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2015, 12, 21)),
        ),
    ]
