# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0007_auto_20151222_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 23, 22, 55, 18, 261490)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2015, 12, 23)),
        ),
    ]
