# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0008_auto_20151220_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.get_current_timezone),
        ),
    ]
