# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0009_auto_20151220_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 20, 4, 9, 14, 427744, tzinfo=utc)),
        ),
    ]
