# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0010_auto_20151225_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 25, 14, 45, 56, 441268)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='postid',
            field=models.IntegerField(),
        ),
    ]
