# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineku', '0015_auto_20151220_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdb',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
